export const weaponNames = [
  "Grim Reaper's Scythe",
  "Ghostly Chainsaw",
  "Lucid Dreamer",
  "Karma's Edge",
  "Bleak Sword",
  "Numbness Fist",
  "Hollow Blade",
  "Eternal Pain",
  "Death Whisperer",
  "Wraith's Hammer",
  "Voidcaller",
  "Nightmare Claws",
  "Obsidian Shard",
  "Doom's Edge",
  "Blood Moon Axe",
  "Blackout Katana",
  "Haze of Despair",
  "Soulbreaker",
  "Drowned Souls Hook",
  "Templespray Crossbow",
  "Chained Heart's Thorn",
  "Cursed Silence",
  "Wraith's Tear",
  "Requiem's Bite",
  "Eternal Decay",
  "Phantom's Fang",
  "Revenant's Grit",
  "Sacred Inferno",
  "Fractured Soulblade",
  "Fury of the Fallen",
  "Crimson Rebirth",
  "Dark Sacrifice Dagger",
  "Now I'm Up To My Neck Cleaver",
  "Soul Drain Scythe",
  "Throne of Ashes Hammer",
];

export const monsterNames = [
  "Sharkboy",
  "Fire Dragon",
  "Stone Golem",
  "Specter of the Void",
  "Titan of the Abyss",
  "Vampire King",
  "Phantom Beast",
  "Death Harbinger",
  "Void Wraith",
  "Cursed Serpent",
  "Omen of Ash",
  "Lurking Shade",
  "Nightmare Knight",
  "Dread Giant",
  "Flesh Eater",
  "Eternal Demon",
  "Abyssal Leviathan",
  "Blight Guardian",
  "Hollow Reaper",
  "Wicked Chimera",
  "Wraith King",
  "Dread Tyrant",
  "Grave Treader",
  "Terror of the Depths",
  "Mad Specter",
  "Sorrowful Phantom",
  "Endless Shadow",
  "Demon of Lament",
  "Ravager of Souls",
  "Frozen Mourner",
  "Vengeful Apparition",
  "Shattered Soul",
  "Fallen Monarch",
  "Cursed Knight",
  "Revenant Behemoth",
  "Berserker Fiend",
  "Scarred Horror",
  "Bleeding Shadow",
  "Cloak of Misery",
  "Skeletal Tyrant",
  "Undying Executioner",
  "Whispering Haunt",
  "Ravaging Beast",
  "Doomed Terror",
  "Shattered Revenant",
  "Tear of the Fallen",
  "Crimson Wraith",
  "Flesh Reaper",
  "Soulmonger",
  "Abyss Wanderer",
  "King of the Endtimes",
  "Cursebringer",
  "Scourge of Hope",
  "Hollow Monarch",
  "Ashen Behemoth",
  "Temple King's Shadow",
  "Chained Demon",
  "Echo of Misery",
];
